services:
  web:
    image: ${APP_IMAGE:-ghcr.io/g2bc/lumm-web}:${IMAGE_TAG:-latest}
    container_name: lumm-web
    restart: unless-stopped
    ports:
      - "4001:80"
    security_opt:
      - no-new-privileges:true
