version: "3.9"
services:
  web:
    build:
      context: .
      target: prod
      args:
        VITE_API_URL: ${VITE_API_URL:?required var}
        VITE_API_KEY: ${VITE_API_KEY:?required var}
    image: lumm-web:prod
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
