version: "3.9"
services:
  web:
    build:
      context: .
      target: dev
      args:
        VITE_API_URL: ${VITE_API_URL:?required var}
        VITE_API_KEY: ${VITE_API_KEY:?required var}
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
