version: "3.9"
services:
  web:
    build:
      context: .
      target: prod
      env_file:
        - .env
    image: ghcr.io/g2bc/lumm:latest
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    restart: unless-stopped