name: Lançar nova release

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    name: Deploy on self-hosted runner
    runs-on: self-hosted

    env:
      APP_DIR: ${{ vars.APP_DIR }}
      IMAGE: ${{ vars.APP_IMAGE }}
      SERVICE: web

    steps:
      - name: Login on GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Update repository
        working-directory: ${{ env.APP_DIR }}
        run: |
          git config --global --add safe.directory "${{ env.APP_DIR }}"
          git pull --ff-only origin main

      - name: Update image and restart container
        working-directory: ${{ env.APP_DIR }}
        run: |
          docker compose up -d --no-deps --pull always --wait --wait-timeout 120 "$SERVICE"

      - name: Show logs on failure
        if: failure()
        working-directory: ${{ env.APP_DIR }}
        run: |
          docker compose ps
          docker compose logs --tail=200 "$SERVICE" || true

      - name: Clean up old images
        run: docker image prune -f
